version: 0.2.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore NyBus.sln
build:
  project: NyBus.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies: '**\Tests.*.dll'