version: 0.5.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore NyBus.sln
- nuget restore packages.config
build:
  project: NyBus.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: FLG2WTxc1Gvrikrvj/UXnb9IAklUhPKGYV5pxOzlwsOWGQBiiEigRnyWCvCc2Zga  
test:
  assemblies: '**\Tests.*.dll'
artifacts:
- path: report.zip
after_test: 
    - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[Nybus.*]*" -target:".\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/process:multiple /noshadow /domain:multiple Nybus.nunit" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
    - packages\ReportGenerator.2.3.1.0\tools\ReportGenerator.exe -reports:coverage.xml -targetdir:Reports
    - 7z a report.zip Reports

