version: 0.2.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore NyBus.sln
- nuget restore packages.config
build:
  project: NyBus.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: FLG2WTxc1Gvrikrvj/UXnb9IAklUhPKGYV5pxOzlwsOWGQBiiEigRnyWCvCc2Zga  
test:
  assemblies: '**\Tests.*.dll'
after_test: 
    - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[Nybus.*]*" -target:".\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single .\tests\Tests.Interfaces\bin\Release\Tests.Interfaces.dll .\tests\Tests.Core\bin\Release\Tests.Core.dll .\tests\Tests.CastleWindsor\bin\Release\Tests.CastleWindsor.dll .\tests\Tests.MassTransit\bin\Release\Tests.MassTransit.dll .\tests\Tests.NLog\bin\Release\Tests.NLog.dll" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
